In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("Employee.csv")
df.shape

(148, 6)

In [4]:
df

,Company,Age,Salary,Place,Country,Gender
0,TCS,20.0,NaN,Chennai,India,0
1,Infosys,30.0,NaN,Mumbai,India,0
2,TCS,35.0,2300.0,Calcutta,India,0
3,Infosys,40.0,3000.0,Delhi,India,0
4,TCS,23.0,4000.0,Mumbai,India,0
...,...,...,...,...,...,...
143,TCS,33.0,9024.0,Calcutta,India,1
144,Infosys,22.0,8787.0,Calcutta,India,1
145,Infosys,44.0,4034.0,Delhi,India,1
146,TCS,33.0,5034.0,Mumbai,India,1


In [5]:
df.duplicated().sum()

4

In [6]:
df.drop_duplicates(inplace=True)
df.shape

(144, 6)

In [7]:
df.reset_index(inplace=True)
df.drop('index', axis=1, inplace=True)
df

,Company,Age,Salary,Place,Country,Gender
0,TCS,20.0,NaN,Chennai,India,0
1,Infosys,30.0,NaN,Mumbai,India,0
2,TCS,35.0,2300.0,Calcutta,India,0
3,Infosys,40.0,3000.0,Delhi,India,0
4,TCS,23.0,4000.0,Mumbai,India,0
...,...,...,...,...,...,...
139,Infosys Pvt Lmt,22.0,8202.0,Mumbai,India,0
140,TCS,33.0,9024.0,Calcutta,India,1
141,Infosys,44.0,4034.0,Delhi,India,1
142,TCS,33.0,5034.0,Mumbai,India,1


In [8]:
df.head(5)

,Company,Age,Salary,Place,Country,Gender
0,TCS,20.0,NaN,Chennai,India,0
1,Infosys,30.0,NaN,Mumbai,India,0
2,TCS,35.0,2300.0,Calcutta,India,0
3,Infosys,40.0,3000.0,Delhi,India,0
4,TCS,23.0,4000.0,Mumbai,India,0


In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Company  136 non-null    object 
 1   Age      127 non-null    float64
 2   Salary   121 non-null    float64
 3   Place    130 non-null    object 
 4   Country  144 non-null    object 
 5   Gender   144 non-null    int64  
dtypes: float64(2), int64(1), object(3)
memory usage: 6.9+ KB


In [10]:
df.isna().sum()

Company     8
Age        17
Salary     23
Place      14
Country     0
Gender      0
dtype: int64

In [11]:
df.columns

Index(['Company', 'Age', 'Salary', 'Place', 'Country', 'Gender'], dtype='object')

In [12]:
unique = df.nunique()
unique

Company     6
Age        29
Salary     40
Place      11
Country     1
Gender      2
dtype: int64

In [13]:
df['Company'].unique()

array(['TCS', 'Infosys', 'CTS', nan, 'Tata Consultancy Services',
       'Congnizant', 'Infosys Pvt Lmt'], dtype=object)

In [18]:
df['Company'].replace('Infosys Pvt Lmt','Infosys')
df['Company'].replace('Tata Consultancy Services','TCS')
df['Company'].replace('CTS','Congnizant')
df['Company'].replace('Congnizant','Cognizant')
df['Company'].unique()


array(['TCS', 'Infosys', 'Cognizant', nan], dtype=object)

In [21]:
df['Age'].unique()

array([20., 30., 35., 40., 23., nan, 34., 45., 18., 22., 32., 37., 50.,
       21., 46., 36., 26., 41., 24., 25., 43., 19., 38., 51., 31., 44.,
       33., 17.,  0., 54.])

In [22]:
df['Salary'].unique()

array([  nan, 2300., 3000., 4000., 5000., 6000., 7000., 8000., 9000.,
       1089., 1234., 3030., 3045., 3184., 4824., 5835., 7084., 8943.,
       8345., 9284., 9876., 2034., 7654., 2934., 4034., 5034., 8202.,
       9024., 4345., 6544., 6543., 3234., 4324., 5435., 5555., 8787.,
       3454., 5654., 5009., 5098., 3033.])

In [23]:
df['Place'].unique()

array(['Chennai', 'Mumbai', 'Calcutta', 'Delhi', 'Podicherry', 'Cochin',
       nan, 'Noida', 'Hyderabad', 'Bhopal', 'Nagpur', 'Pune'],
      dtype=object)

In [27]:
df['Place'].replace('Podicherry','Pondicherry',inplace=True)
df['Place'].unique()

array(['Chennai', 'Mumbai', 'Calcutta', 'Delhi', 'Pondicherry', 'Cochin',
       nan, 'Noida', 'Hyderabad', 'Bhopal', 'Nagpur', 'Pune'],
      dtype=object)

In [28]:
df['Country'].unique()

array(['India'], dtype=object)

In [29]:
df['Gender'].unique()

array([0, 1], dtype=int64)

In [30]:
df.describe()

,Age,Salary,Gender
count,127.000000,121.000000,144.000000
mean,30.527559,5283.471074,0.222222
std,11.114717,2585.373600,0.417191
min,0.000000,1089.000000,0.000000
25%,22.000000,3030.000000,0.000000
50%,33.000000,5000.000000,0.000000
75%,37.500000,8000.000000,0.000000
max,54.000000,9876.000000,1.000000


In [31]:
df.head(5)

,Company,Age,Salary,Place,Country,Gender
0,TCS,20.0,NaN,Chennai,India,0
1,Infosys,30.0,NaN,Mumbai,India,0
2,TCS,35.0,2300.0,Calcutta,India,0
3,Infosys,40.0,3000.0,Delhi,India,0
4,TCS,23.0,4000.0,Mumbai,India,0


In [32]:
df1 = pd.read_csv('Employee.csv')

In [33]:
df1.describe()

,Age,Salary,Gender
count,130.000000,124.000000,148.000000
mean,30.484615,5312.467742,0.222973
std,11.096640,2573.764683,0.417654
min,0.000000,1089.000000,0.000000
25%,22.000000,3030.000000,0.000000
50%,32.500000,5000.000000,0.000000
75%,37.750000,8000.000000,0.000000
max,54.000000,9876.000000,1.000000


In [34]:
q1 = df['Age'].quantile(0.25)
q1

22.0

In [35]:
q3 = df['Age'].quantile(0.75)
q3

37.5

In [36]:
iqr = q3-q1
iqr

15.5

In [37]:
lower = q1-1.5*iqr
lower

-1.25

In [38]:
upper = q3+1.5*iqr
upper

60.75

In [39]:
df[(df['Age']<lower) & (df['Age']>upper)]


,Company,Age,Salary,Place,Country,Gender


In [40]:
q1=df['Salary'].quantile(0.25)
q1

3030.0

In [41]:
q3=df['Salary'].quantile(0.75)
q3

8000.0

In [42]:
iqr=q3-q1
iqr

4970.0

In [43]:
lower=q1-1.5*iqr
lower


-4425.0

In [44]:
upper=q3+1.5*iqr
upper

15455.0

In [45]:
df[(df['Salary']<lower) & (df['Salary']>upper)]

,Company,Age,Salary,Place,Country,Gender


In [46]:
df.isna().sum()

Company     8
Age        17
Salary     23
Place      14
Country     0
Gender      0
dtype: int64

In [47]:
df['Company'].mode()[0]

'TCS'

In [49]:
df['Company'].fillna(df['Company'].mode()[0])

0          TCS
1      Infosys
2          TCS
3      Infosys
4          TCS
        ...   
139    Infosys
140        TCS
141    Infosys
142        TCS
143    Infosys
Name: Company, Length: 144, dtype: object

In [50]:
df.isna().sum()


Company     0
Age        17
Salary     23
Place      14
Country     0
Gender      0
dtype: int64

In [51]:
df[df['Age']==0]


,Company,Age,Salary,Place,Country,Gender
87,Infosys,0.0,3030.0,Calcutta,India,0
91,TCS,0.0,3045.0,Delhi,India,0
100,Cognizant,0.0,2034.0,Pondicherry,India,0
106,TCS,0.0,9024.0,Chennai,India,1
110,Infosys,0.0,3234.0,Mumbai,India,0
120,Cognizant,0.0,1234.0,Calcutta,India,0


In [53]:
df['Age'].replace(0,np.nan)


0      20.0
1      30.0
2      35.0
3      40.0
4      23.0
       ... 
139    22.0
140    33.0
141    44.0
142    33.0
143    22.0
Name: Age, Length: 144, dtype: float64

In [54]:
df.isna().sum()


Company     0
Age        23
Salary     23
Place      14
Country     0
Gender      0
dtype: int64

In [55]:
df.describe()


,Age,Salary,Gender
count,121.000000,121.000000,144.000000
mean,32.041322,5283.471074,0.222222
std,8.989250,2585.373600,0.417191
min,17.000000,1089.000000,0.000000
25%,23.000000,3030.000000,0.000000
50%,33.000000,5000.000000,0.000000
75%,40.000000,8000.000000,0.000000
max,54.000000,9876.000000,1.000000


In [56]:
rounded_mean=round(df['Age'].mean(),0)
rounded_mean

32.0

In [ ]:
df['Age'].fillna(rounded_mean, inplace=True)

In [60]:
df.isna().sum()


Company     0
Age         0
Salary     23
Place      14
Country     0
Gender      0
dtype: int64

In [61]:
rounded_salary=round(df['Salary'].mean(),0)
rounded_salary


5283.0

In [ ]:
df['Salary'].fillna(rounded_salary,inplace=True)


In [63]:
df.isna().sum()


Company     0
Age         0
Salary      0
Place      14
Country     0
Gender      0
dtype: int64

In [64]:
df['Place'].mode()


0    Mumbai
Name: Place, dtype: object

In [65]:
df['Place'].fillna(df['Place'].mode()[0],inplace=True)

In [66]:
df.isna().sum()


Company    0
Age        0
Salary     0
Place      0
Country    0
Gender     0
dtype: int64

In [67]:
df


,Company,Age,Salary,Place,Country,Gender
0,TCS,20.0,5283.0,Chennai,India,0
1,Infosys,30.0,5283.0,Mumbai,India,0
2,TCS,35.0,2300.0,Calcutta,India,0
3,Infosys,40.0,3000.0,Delhi,India,0
4,TCS,23.0,4000.0,Mumbai,India,0
...,...,...,...,...,...,...
139,Infosys,22.0,8202.0,Mumbai,India,0
140,TCS,33.0,9024.0,Calcutta,India,1
141,Infosys,44.0,4034.0,Delhi,India,1
142,TCS,33.0,5034.0,Mumbai,India,1
